name: Code Coverage Report
description: Comments a pull request with the code coverage
author: Romeo Van Snick
branding:
  icon: check-square
  color: green
inputs:
  lcov-file:
    description: The location of the lcov.info file
    required: false
    default: ./coverage/lcov.info
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
runs:
  using: node12
  main: dist/main.js
